-- Mysql DDL 문을 연관관계 맞게 작성
-- column 명 중에 YYYY나 RN이 들어가면 datatype은 varchar2(50)
-- PRIMARY KEY는 table 내 한 column 사용
-- table 1 : NSC2_BND(column : RN_INDI BTH_YYYY DTH_YYYYMM COD1 COD2)
-- table 2 : NSC2_BNC_V2_1(column : STD_YYYY RN_INDI SEX SGG GAIBJA_TYPE CTRB_Q10 DSB_TYPE_CD G1E_OBJ_YN SMPL_TYPE_CD DSB_SVRT_CD_V2)

-- NSC2_BND 테이블 생성
CREATE TABLE NSC2_BND (
  RN_INDI VARCHAR(50) PRIMARY KEY,
  BTH_YYYY VARCHAR(50),
  DTH_YYYYMM VARCHAR(50),
  COD1 VARCHAR(20),
  COD2 VARCHAR(20)
);

-- NSC2_BNC_V2_1 테이블 생성
CREATE TABLE NSC2_BNC_V2_1 (
  STD_YYYY VARCHAR(50),
  RN_INDI VARCHAR(50),
  SEX CHAR(1),
  SGG VARCHAR(10),
  GAIBJA_TYPE VARCHAR(10),
  CTRB_Q10 VARCHAR(50),
  DSB_TYPE_CD VARCHAR(10),
  G1E_OBJ_YN CHAR(1),
  SMPL_TYPE_CD VARCHAR(10),
  DSB_SVRT_CD_V2 VARCHAR(10),
  PRIMARY KEY (RN_INDI),
  FOREIGN KEY (RN_INDI) REFERENCES NSC2_BND (RN_INDI)
);
