
CREATE TABLE FILES
(
  FILE           VARCHAR(200) NULL     COMMENT '첨부파일',
  FILE_UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '파일 대표값',
  PRIMARY KEY (FILE_UNIQUE_ID)
) COMMENT '첨부파일';

CREATE TABLE FILES_LIST
(
  NO_UNIQUE_ID   VARCHAR(200) NOT NULL COMMENT '공지사항 대표값',
  FILE_UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '파일 대표값',
  PRIMARY KEY (NO_UNIQUE_ID, FILE_UNIQUE_ID)
);

CREATE TABLE NOTICES
(
  NO_UNIQUE_ID     VARCHAR(200) NOT NULL COMMENT '공지사항 대표값',
  NO.              VARCHAR(200) NULL     COMMENT '공지번호',
  TITLE            VARCHAR(200) NULL     COMMENT '제목',
  FILE             VARCHAR(200) NULL     COMMENT '첨부파일',
  CREATED_DATE     VARCHAR(200) NULL     COMMENT '작성일',
  VIEW             INTEGER      NULL     COMMENT '조회수',
  WRITER_UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '작성자 대표값',
  PRIMARY KEY (NO_UNIQUE_ID)
) COMMENT '공지사항';

CREATE TABLE WIRTERS
(
  WRITER_UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '작성자 대표값',
  WRITER           VARCHAR(200) NOT NULL COMMENT '작성자',
  PRIMARY KEY (WRITER_UNIQUE_ID)
) COMMENT '작성자';

ALTER TABLE FILES_LIST
  ADD CONSTRAINT FK_NOTICES_TO_FILES_LIST
    FOREIGN KEY (NO_UNIQUE_ID)
    REFERENCES NOTICES (NO_UNIQUE_ID);

ALTER TABLE FILES_LIST
  ADD CONSTRAINT FK_FILES_TO_FILES_LIST
    FOREIGN KEY (FILE_UNIQUE_ID)
    REFERENCES FILES (FILE_UNIQUE_ID);

ALTER TABLE NOTICES
  ADD CONSTRAINT FK_WIRTERS_TO_NOTICES
    FOREIGN KEY (WRITER_UNIQUE_ID)
    REFERENCES WIRTERS (WRITER_UNIQUE_ID);
